# Generated by Django 4.2.4 on 2023-09-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0002_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contributor",
            field=models.ManyToManyField(to="projects.projects"),
        ),
    ]
