# Generated by Django 4.2.4 on 2023-09-04 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=30, verbose_name="titre_du_projet"),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=2048, verbose_name="description_du_projet"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BACK_END", "BACK_END"),
                            ("FRONT_END", "FRONT_END"),
                            ("IOS", "IOS"),
                            ("ANDROID", "ANDROID"),
                        ],
                        max_length=30,
                        verbose_name="Type_de_projet",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auteur_projet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
