# Generated by Django 4.2.4 on 2023-09-04 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_contributor"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issues",
            fields=[
                (
                    "description",
                    models.TextField(
                        max_length=2048, verbose_name="description_du_probleme"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO_DO", "TO_DO"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("FINISHED", "FINISHED"),
                        ],
                        max_length=30,
                        verbose_name="priorite",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                        ],
                        max_length=30,
                        verbose_name="priorite",
                    ),
                ),
                (
                    "balise",
                    models.CharField(
                        choices=[
                            ("BUG", "BUG"),
                            ("TASK", "TASK"),
                            ("FEATURE", "FEATURE"),
                        ],
                        max_length=30,
                        verbose_name="balise",
                    ),
                ),
                (
                    "assignee_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="utilisateur_affecté",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projet",
                        to="projects.projects",
                    ),
                ),
            ],
        ),
    ]
