# Generated by Django 4.2.5 on 2023-09-06 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0003_comments_title_issues_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="title",
            field=models.CharField(max_length=100, verbose_name="titre du commentaire"),
        ),
        migrations.AlterField(
            model_name="issues",
            name="title",
            field=models.CharField(max_length=100, verbose_name="titre de la tache"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_projet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="title",
            field=models.CharField(max_length=100, verbose_name="titre du projet"),
        ),
    ]
